[package]
name = "libfuse-fs"
version = "0.1.4"
edition = "2024"
description = "FUSE Filesystem Library"
homepage = "https://github.com/r2cn-dev/rk8s/tree/main/project/libfuse-fs"
repository = "https://github.com/r2cn-dev/rk8s/tree/main/project/libfuse-fs"
documentation = "https://github.com/r2cn-dev/rk8s/tree/main/project/libfuse-fs"
license = "mit or apache-2.0"
exclude = ["buck"]

[dependencies]
uuid = { version = "1.15.1", features = ["v4"] }
clap = { version = "4.5.32", features = ["derive"] }
rfuse3 = { version = "0.0.4", features = ["tokio-runtime", "unprivileged"] }
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter"] }
tokio = { version = "1.44.0", features = ["full"] }
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
radix_trie = "0.2.1"
futures = "0.3.31"
libc = "0.2.171"
serde_json = "1.0.128"
vm-memory = "0.16.1"
bytes = "1.10.1"
futures-util = "0.3.31"
vmm-sys-util = "0.12.1"
bitflags = "2.9.0"
nix = "0.29.0"
moka = { version = "0.12.11", features = ["future"] }
memmap2 = "0.9.7"
tracing = "0.1.41"
itertools = "0.14.0"
async-trait = "0.1.89"

[dev-dependencies]
tempfile = "3.19.1"